steps:
  #build docker container

  - name: 'gcr.io/absolute-vertex-328512/docker'
    args: [ 'build', '-t', 'gcr.io/absolute-vertex-328512/batch-processing-app', '.']

  #push container to container registry
  - name: 'gcr.io/absolute-vertex-328512/docker'
    args: [ 'push', 'gcr.io/absolute-vertex-328512/batch-processing-app']

  #deploy to cloud run
  - name: 'gcr.io/absolute-vertex-328512/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrunservice'
      - '--image'
      - 'gcr.io/absolute-vertex-328512/batch-processing-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/absolute-vertex-328512/batch-processing-app'

#  - id: push image
#    name: 'gcr.io/cloud-builders/docker'
#    args: [ 'push', 'gcr.io/absolute-vertex-328512/batch-processing:1.11-SNAPSHOT' ]

options:
  logging: CLOUD_LOGGING_ONLY