steps:
  #build maven
  - name: 'maven:3-jdk-8'
    entrypoint: mvn
    args: ['clean','install']

  #build docker container
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/absolute-vertex-328512/batch-processing-app', '.']

  #push container to container registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: docker
    args: [ 'push', 'gcr.io/absolute-vertex-328512/batch-processing-app']

  #deploy to cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cloudrunservice'
      - '--image'
      - 'gcr.io/absolute-vertex-328512/batch-processing-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/absolute-vertex-328512/batch-processing-app'

options:
  logging: CLOUD_LOGGING_ONLY